I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 47, in script
    show FGnoHands at center, z0
  File "game/script.rpy", line 47, in <module>
    show FGnoHands at center, z0
NameError: name 'z0' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 47, in script
    show FGnoHands at center, z0
  File "C:\Users\Luke Moulton\Desktop\RenPy8\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Luke Moulton\Desktop\RenPy8\renpy\ast.py", line 1387, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\Luke Moulton\Desktop\RenPy8\renpy\ast.py", line 1387, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\Luke Moulton\Desktop\RenPy8\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Luke Moulton\Desktop\RenPy8\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 47, in <module>
    show FGnoHands at center, z0
NameError: name 'z0' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Timpbus 1.0
Wed Jan 24 14:28:08 2024
